# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=254)),
                ('keyword', models.CharField(max_length=254)),
                ('resultcount', models.CharField(max_length=10)),
                ('searchdate', models.DateField()),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searchs',
                'db_table': 'connector_search',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'SearchResult',
                'verbose_name_plural': 'SearchResults',
                'db_table': 'connector_searchresult',
                'managed': True,
            },
        ),
    ]
