# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_name', models.CharField(max_length=200)),
                ('copy_connector_id', models.IntegerField(max_length=11)),
                ('created_by_id', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='searchdate',
            field=models.DateTimeField(),
        ),
    ]
