# Generated by Django 2.0.5 on 2018-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_auto_20180507_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('Connect Req', 'Connect Req')], default='Connect Req', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectorcampaign',
            name='connectors',
            field=models.ManyToManyField(to='messenger.Inbox'),
        ),
    ]
