# Generated by Django 2.0.5 on 2018-05-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20180510_1339'),
        ('connector', '0005_auto_20180508_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('Replied', 'Replied'), ('Talking', 'Talking'), ('Talking & Replied', 'Talking & Replied'), ('Connect Req', 'Connect Req')], default='Talking', max_length=50)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_messages', to='connector.ConnectorCampaign')),
                ('requestee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestees', to='messenger.Inbox')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
