# Generated by Django 2.0.5 on 2018-05-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('connector', '0006_connectmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Error', 'Error'), ('Done', 'Done')], default='Queued', max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('queue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
