# Generated by Django 2.0.5 on 2018-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_taskqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectmessage',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectmessage',
            name='is_replied_other',
            field=models.BooleanField(default=False),
        ),
    ]
