# Generated by Django 2.0.5 on 2018-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20180511_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectmessage',
            old_name='is_replied',
            new_name='is_bulk',
        ),
        migrations.AddField(
            model_name='connectmessage',
            name='replied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectmessage',
            name='replied_other_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
