# Generated by Django 2.0.5 on 2018-05-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0009_auto_20180511_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectmessage',
            name='is_bulk',
        ),
        migrations.RemoveField(
            model_name='connectmessage',
            name='replied_date',
        ),
        migrations.RemoveField(
            model_name='connectmessage',
            name='replied_other_date',
        ),
    ]
