# Generated by Django 2.0.5 on 2018-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0010_auto_20180511_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
