# Generated by Django 2.0.5 on 2018-05-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_auto_20180513_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectmessage',
            name='type',
            field=models.CharField(blank=True, choices=[(10, 'Replied'), (12, 'Talking'), (100, 'Talking & Replied'), (5, 'Connect Req')], default='Talking', max_length=50),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Queue'), (5, 'Connect Req')], default=5),
        ),
    ]
