# Generated by Django 2.0.5 on 2018-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_auto_20180514_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='company',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='industry',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
