# Generated by Django 2.0.5 on 2018-05-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_auto_20180513_2202'),
        ('connector', '0013_auto_20180514_1037'),
    ]

    operations = [
    ]
