# Generated by Django 2.0.5 on 2018-05-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0014_merge_20180514_1803'),
        ('connector', '0011_auto_20180513_0943'),
    ]

    operations = [
    ]
