# Generated by Django 2.0.5 on 2018-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0015_merge_20180515_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskqueue',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Pin Required', 'Pin Required'), ('Pin Checking', 'Pin Checking'), ('Pin Invalid', 'Pin Invalid'), ('Error', 'Error'), ('Done', 'Done')], default='Queued', max_length=20),
        ),
    ]
