# Generated by Django 2.0.5 on 2018-05-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_auto_20180515_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='resultcount',
            field=models.IntegerField(default=0),
        ),
    ]
