# Generated by Django 2.0.5 on 2018-05-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0017_auto_20180516_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='resultcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
