# Generated by Django 2.0.5 on 2018-05-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0018_auto_20180516_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'In Queue'), (5, 'Connect Req')], null=True),
        ),
    ]
