# Generated by Django 2.0.5 on 2018-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0021_searchresult_connect_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Queue'), (5, 'Connect Req')], default=1),
        ),
    ]
