# Generated by Django 2.0.5 on 2018-05-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0022_auto_20180517_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Queue'), (5, 'Connect Req')], default=5),
        ),
    ]
