# Generated by Django 2.0.5 on 2018-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0023_auto_20180517_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
