# Generated by Django 2.0.5 on 2018-05-18 08:45

from django.db import migrations, models
import django.utils


    
class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0025_taskqueue_due_date'),
    ]
    
    

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='latest_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='linkedin_id',
            field=models.CharField(max_length=50, null=True),
            preserve_default=False,
        ),
        
    ]
