# Generated by Django 2.0.5 on 2018-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0028_auto_20180518_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
