# Generated by Django 2.0.5 on 2018-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0029_auto_20180518_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='latest_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
