# Generated by Django 2.0.5 on 2018-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0031_auto_20180521_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='sales_search',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='url_search',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
