# Generated by Django 2.0.5 on 2018-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0033_searchresult_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
