# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('visitcount', models.IntegerField(max_length=4)),
            ],
        ),
    ]
