# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
