# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
