# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180503_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('enable_proxy', models.BooleanField(default=0)),
                ('proxy_address', models.CharField(blank=True, max_length=60, null=True)),
                ('proxy_authentication_type', models.CharField(max_length=254)),
                ('proxy_username', models.CharField(blank=True, max_length=254, null=True)),
                ('proxy_password', models.CharField(blank=True, max_length=254, null=True)),
                ('license_type', models.CharField(max_length=254)),
            ],
        ),
    ]
