# Generated by Django 2.0.5 on 2018-05-08 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20180507_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_seat', models.IntegerField(default=1)),
                ('max_search', models.IntegerField(default=5)),
                ('max_search_result', models.IntegerField(default=500)),
                ('price', models.FloatField(default=0.0)),
                ('max_campaign', models.IntegerField(default=5)),
                ('twoway_comm', models.BooleanField(default=True)),
                ('welcome_message', models.BooleanField(default=True)),
                ('custom_connect_message', models.BooleanField(default=False)),
                ('company_title_search', models.BooleanField(default=False)),
                ('withdrawn_invite', models.BooleanField(default=False)),
                ('expoert_csv', models.BooleanField(default=False)),
                ('day_to_live', models.IntegerField(default=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='company_title_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='custom_connect_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='day_to_live',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='expoert_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='max_campaign',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='max_search_result',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='twoway_comm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='welcome_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='withdrawn_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='max_search',
            field=models.IntegerField(default=5),
        ),
    ]
