# Generated by Django 2.0.5 on 2018-05-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180508_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='expoert_csv',
            new_name='export_csv',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='expoert_csv',
            new_name='export_csv',
        ),
    ]
