# Generated by Django 2.0.5 on 2018-05-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180508_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='linkedusers', to='app.Profile'),
            preserve_default=False,
        ),
    ]
