# Generated by Django 2.0.5 on 2018-05-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_linkedinuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='is_weekendwork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='membership',
            field=models.ManyToManyField(to='app.Membership'),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='start_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='start_to',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='tz',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
