# Generated by Django 2.0.5 on 2018-05-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180510_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userserver',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='UserServer',
        ),
    ]
