# Generated by Django 2.0.5 on 2018-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180511_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='is_pin_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
