# Generated by Django 2.0.5 on 2018-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180513_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinuser',
            name='is_pin_needed',
        ),
        migrations.AlterField(
            model_name='linkedinuser',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Pin Required', 'Pin Required'), ('Pin Invalid', 'Pin Invalid'), ('Error', 'Error'), ('Done', 'Done')], default='Queued', max_length=20),
        ),
    ]
