# Generated by Django 2.0.5 on 2018-05-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180514_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottask',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Pin Required', 'Pin Required'), ('Pin Checking', 'Pin Checking'), ('Pin Invalid', 'Pin Invalid'), ('Error', 'Error'), ('Done', 'Done')], default='Queued', max_length=20),
        ),
    ]
