# Generated by Django 2.0.5 on 2018-05-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180514_1944'),
        ('app', '0018_auto_20180513_1156'),
    ]

    operations = [
    ]
