# Generated by Django 2.0.5 on 2018-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180515_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='login_status',
            field=models.CharField(blank=True, choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Pin Required', 'Pin Required'), ('Pin Checking', 'Pin Checking'), ('Pin Invalid', 'Pin Invalid'), ('Error', 'Error'), ('Done', 'Done')], max_length=50, null=True),
        ),
    ]
