# Generated by Django 2.0.5 on 2018-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_linkedinuser_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinuser',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]

    def __init__(self, name, app_label):
        super(Migration, self).__init__(name, app_label)
        print('Migration name:', self)