# Generated by Django 2.0.5 on 2018-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180519_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottask',
            name='extra_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
