# Generated by Django 2.0.5 on 2018-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_bottask_extra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='bot_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
