# Generated by Django 2.0.5 on 2018-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_linkedinuser_bot_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBotIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
