# Generated by Django 2.0.5 on 2018-05-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_freebotip'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='last_message_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
