# Generated by Django 2.0.5 on 2018-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_adminemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='message_limit',
            field=models.IntegerField(default=0),
        ),
    ]
