# Generated by Django 2.0.5 on 2018-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_linkedinuser_message_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinuser',
            name='message_limit',
            field=models.IntegerField(default=75),
        ),
    ]
