# Generated by Django 2.0.5 on 2018-06-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20180606_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinuser',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
    ]
