# Generated by Django 2.0.5 on 2018-05-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_auto_20180507_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignStepField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(db_index=True, default=1)),
                ('message', models.TextField()),
                ('action', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('latest_acitvity', models.DateTimeField()),
                ('connector_messenger', models.CharField(choices=[('Imported', 'Imported'), ('In Queue', 'In Queue')], default='Imported', max_length=20)),
                ('status', models.CharField(choices=[('All', 'All'), ('Later', 'Later'), ('No Interest', 'No Interest'), ('Old Connect', 'Old Connect'), ('Replied', 'Replied'), ('Talking', 'Talking'), ('Talking & Replied', 'Talking & Replied')], default='Old Connect', max_length=20)),
                ('notes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.LinkedInUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('latest_acitvity', models.DateTimeField()),
                ('status', models.CharField(choices=[('All', 'All'), ('Later', 'Later'), ('No Interest', 'No Interest'), ('Old Connect', 'Old Connect'), ('Replied', 'Replied'), ('Talking', 'Talking'), ('Talking & Replied', 'Talking & Replied'), ('Connected', 'Connected'), ('Old Connect', 'Old Connect'), ('Disconnected', 'Disconnected'), ('In Queue', 'In Queue'), ('Welcome Mes', 'Welcome Mes')], default='Old Connect', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='app.LinkedInUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='messenger.Contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='app.LinkedInUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('campaignstepfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.CampaignStepField')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('messenger.campaignstepfield', models.Model),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(to='messenger.Contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='copy_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.Campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messegercampaigns', to='app.LinkedInUser'),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaignsteps', to='messenger.Campaign'),
        ),
    ]
