# Generated by Django 2.0.5 on 2018-05-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
        migrations.AddField(
            model_name='inbox',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(to='messenger.Inbox'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='messenger.Inbox'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
