# Generated by Django 2.0.5 on 2018-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20180510_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='connected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
