# Generated by Django 2.0.5 on 2018-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_inbox_connected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
