# Generated by Django 2.0.5 on 2018-05-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20180511_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_bulk',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_other_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='replied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='replied_other_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
