# Generated by Django 2.0.5 on 2018-05-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20180511_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('Replied', 'Replied'), ('Talking', 'Talking'), ('Talking & Replied', 'Talking & Replied'), ('Connect Req', 'Connect Req')], default='Talking', max_length=50)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='messenger.Inbox')),
                ('messenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_messages', to='messenger.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messenger',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
