# Generated by Django 2.0.5 on 2018-05-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_auto_20180511_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='replied_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='replied_other_date',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='messenger',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='messagestep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_messages', to='messenger.CampaignStep'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='replied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='replied_other_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
