# Generated by Django 2.0.5 on 2018-05-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20180511_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='messagestep',
        ),
        migrations.AddField(
            model_name='campaign',
            name='connection_message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='welcome_message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='campaignstepfield',
            name='step_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to='messenger.Campaign'),
        ),
    ]
