# Generated by Django 2.0.5 on 2018-05-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_auto_20180511_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='latest_acitvity',
            new_name='latest_activity',
        ),
    ]
