# Generated by Django 2.0.5 on 2018-05-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_auto_20180512_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='welcome_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
