# Generated by Django 2.0.5 on 2018-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_auto_20180513_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(related_name='campaigns', to='messenger.Inbox'),
        ),
    ]
