# Generated by Django 2.0.5 on 2018-05-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0016_auto_20180514_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
