# Generated by Django 2.0.5 on 2018-05-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180514_1944'),
        ('messenger', '0017_inbox_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='app.LinkedInUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='messenger.ChatMessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='messenger.Inbox'),
        ),
    ]
