# Generated by Django 2.0.5 on 2018-05-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_auto_20180515_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_direct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
