# Generated by Django 2.0.5 on 2018-05-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_auto_20180515_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='status',
            field=models.IntegerField(choices=[(-1, 'All'), (200, 'Unread'), (3, 'Connected'), (1, 'Connect Requested'), (23, 'Disconnected'), (0, 'In Queue'), (21, 'No Interest'), (20, 'Later'), (7, 'Message'), (22, 'Old Connect'), (10, 'Replied'), (12, 'Talking'), (100, 'Talking & Replied'), (6, 'Welcome Mes')], default=22),
        ),
    ]
