# Generated by Django 2.0.5 on 2018-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0021_auto_20180519_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='linkedin_id',
            field=models.CharField(max_length=50),
        ),
    ]
