# Generated by Django 2.0.5 on 2018-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0022_auto_20180521_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
