# Generated by Django 2.0.5 on 2018-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0023_chatmessage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
