# Generated by Django 2.0.5 on 2018-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0024_inbox_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='countrycode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
