# Generated by Django 2.0.5 on 2018-06-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0027_remove_inbox_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
