# Generated by Django 2.0.5 on 2018-06-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0029_remove_chatmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='campaignstep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='messenger.CampaignStep'),
        ),
    ]
